apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: endpoint-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "endpoint-ingress"
spec:
  backend:
    serviceName: endpoint-service
    servicePort: endpoint-http
