apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: hub
spec:
 replicas: 2
 template:
   metadata:
     labels:
       app: hubapp
   spec:
     containers:
       - name: hubapp
         image: gcr.io/jokerchat/jokerchat.hub:0.13
         ports:
           - containerPort: 80
         env:
          - name: ASPNETCORE_URLS
            value: "http://0.0.0.0:80"
          - name: ASPNETCORE_ENVIRONMENT
            value: "Kubernetes"
